### ISSUE TITLE
4章 Q36, Q37のアルファブレンドの模範解答

### ISSUE THREAD

**Issue by ma38su** [koshian2/numpy-book#2]
インフィニティnumpyの4章、Q36, Q37の模範解答について質問させてください。

模範解答では、アルファブレンドについて以下の実装が示されています。

```
img_o_a = img_s[:,:,3:4] + img_d[:,:,3:4]*(1- img_s[:,:,3:4])
img_o_rgb = (img_s[:,:,:3]*img_s[:,:,3:4] + img_d[:,:,:3]*img_d[:,:,3:4])/img_o_a
img_o_rgb[np.isnan(img_o_rgb)] = 0.0
```

ただ、本文中に示されている式を忠実に再現すると、
以下のように、img_o_rgbの合成にも、```(1- img_s[:,:,3:4])```をかける必要があると思ったのですが、
不要なのでしょうか？

```
img_o_a = img_s[:,:,3:4] + img_d[:,:,3:4]*(1- img_s[:,:,3:4])
img_o_rgb = (img_s[:,:,:3]*img_s[:,:,3:4] + img_d[:,:,:3]*img_d[:,:,3:4]*(1 - img_s[:,:,3:4])) / img_o_a
img_o_rgb[np.isnan(img_o_rgb)] = 0.0
```

**Comment by koshian2** [comment]
@ma38su 
ご報告ありがとうございます。ご指摘の通り```(1- img_s[:,:,3:4])```を掛けるのが正しいです。掛けるのを忘れてしまいました。
模範解答のColab Notebookを修正し、正誤表に記載いたしました。
ご迷惑をおかけしたことをお詫びいたします。

**Comment by ma38su** [comment]
回答ありがとうございました。
(とても楽しんで演習取り組ませて頂いてます。)
